### ISSUE TITLE
Oops! We encountered an unexpected error. Please try again.

### ISSUE THREAD

**Issue by Zoemmie** [masterking32/twitch-account-creator#21] opened 2022-09-23 19:49 UTC
Hi, getting that error every time. With and without proxy.

Captcha found, registering account ...
Oops! We encountered an unexpected error. Please try again.
Username: turnaboutgrand019
Username: turnaboutgrand019 Password:mpQHexKeYD_MK32 BDay: 1973/10/2
Getting email
Solving captcha
Using 2Captcha.
Request sent to the 2captcha wait a bit, Request ID: 71588334505
Wating to reslove ... (15 - 300 sec)

Thanks in advance.

**Comment by magusin** [comment] 2022-09-27 22:04
i get same

**Comment by 12Echo** [comment] 2022-10-13 05:41
Same happening for me, gonna try to see why

**Comment by Nagrom33** [comment] 2022-10-21 07:03
Got the same over here, can't find why

**Comment by TeamNoxious** [comment] 2022-10-23 03:29
No fix for this yet? Im getting the same issue...

**Comment by TeamNoxious** [comment] 2022-10-31 20:46
> > 
> 
> 
> 
> Thanks, could you add me for better contact - xyss#5770

Sure no problem.

**Comment by masterking32** [comment] 2022-11-03 01:56
I checked that,
Now Twitch using: https://www.kasada.io/
The issue is about `Client-Integrity`.
For registration, We need an `integrity_token`.
To get `integrity_token`, We need to send the request to `passport.twitch.tv` with `x-kpsdk-cd` and `x-kpsdk-ct`.
I know how to get `x-kpsdk-ct` but I don't know about `x-kpsdk-cd`.
So the project is not working for now ...
If I figure out how to solve that, I will commit to solving the problem.

**Comment by NicNem55** [comment] 2022-11-03 12:50
no solution found?

**Comment by danikishin** [comment] 2022-12-21 05:15
> I checked that, Now Twitch using: https://www.kasada.io/ The issue is about `Client-Integrity`. For registration, We need an `integrity_token`. To get `integrity_token`, We need to send the request to `passport.twitch.tv` with `x-kpsdk-cd` and `x-kpsdk-ct`. I know how to get `x-kpsdk-ct` but I don't know about `x-kpsdk-cd`. So the project is not working for now ... If I figure out how to solve that, I will commit to solving the problem.

an you tell me how to obtain x-kpsdk-ct? I am also trying to figure this out and any information may be helpful.

**Comment by sheldygg** [comment] 2023-02-05 23:36
> I checked that, Now Twitch using: https://www.kasada.io/ The issue is about `Client-Integrity`. For registration, We need an `integrity_token`. To get `integrity_token`, We need to send the request to `passport.twitch.tv` with `x-kpsdk-cd` and `x-kpsdk-ct`. I know how to get `x-kpsdk-ct` but I don't know about `x-kpsdk-cd`. So the project is not working for now ... If I figure out how to solve that, I will commit to solving the problem.

I know how to get `x-kpsdk-cd`, tell me how to get it and I will help you with `x-kpsdk-cd`

**Comment by masterking32** [comment] 2023-02-09 10:47
Ok now project work, I need to close the issue.

**Closed by masterking32** 2023-02-09 10:47 UTC
